[package]
name = "kson-sys"
version = "0.1.0"
edition = "2024"
links = "kson"

[features]
default = []
dynamic-linking = []

[build-dependencies]
bindgen = "0.71.0"

[dev-dependencies]
insta = "1.43.1"
