[workspace]
authors = ["Adolfo Ochagavía <github@adolfo.ochagavia.nl>"]
channels = ["conda-forge"]
name = "language-server-protocol"
platforms = [
    "linux-64",
    "linux-aarch64",
    "osx-arm64",
    "osx-64",
    "win-64",
]
version = "0.1.0"

[tasks]

[dependencies]
nodejs = "20.19.4.*"
python = "3.13.*"

[target.win-64.dependencies]
vc14_runtime = "14.44.*"
