[workspace]
authors = ["Adolfo Ochagavía <github@adolfo.ochagavia.nl>"]
channels = ["conda-forge"]
name = "lib-rust"
platforms = [
    "linux-64",
    "linux-aarch64",
    "osx-arm64",
    "osx-64",
    "win-64",
]
version = "0.1.0"

[tasks]

[dependencies]
rust = "1.89.0.*"

[target.win-64.dependencies]
vc14_runtime = "14.44.*"

[target.linux-64.dependencies]
libclang = "20.*"

[target.linux-aarch64.dependencies]
libclang = "20.*"
